// <auto-generated />
using System;
using EFCF1.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCF1.Migrations
{
    [DbContext(typeof(EmployeeManagement))]
    partial class EmployeeManagementModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCF1.Model.Dept", b =>
            {
                b.Property<int>("Depno")
                    .HasColumnType("int");

                b.Property<string>("Dname")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Depno");

                b.ToTable("Depts");
            });

            modelBuilder.Entity("EFCF1.Model.Emp", b =>
            {
                b.Property<int>("Empno")
                    .HasColumnType("int");

                b.Property<string>("Addr")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Deptno")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Deptno"));

                b.Property<int?>("DeptnonavDepno")
                    .HasColumnType("int");

                b.Property<string>("Ename")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Empno");

                b.HasIndex("DeptnonavDepno");

                b.ToTable("Emps");
            });

            modelBuilder.Entity("EFCF1.Model.Emp", b =>
            {
                b.HasOne("EFCF1.Model.Dept", "Deptnonav")
                    .WithMany("Emps")
                    .HasForeignKey("DeptnonavDepno");

                b.Navigation("Deptnonav");
            });

            modelBuilder.Entity("EFCF1.Model.Dept", b =>
            {
                b.Navigation("Emps");
            });
#pragma warning restore 612, 618
        }
    }
}
